FROM archlinux:latest

LABEL org.opencontainers.image.title="Syndra Purple Team"
LABEL org.opencontainers.image.description="Isolated Purple Team toolkit (Red + Blue) for Syndra"

RUN pacman -Syu --noconfirm \
    && pacman -S --needed --noconfirm \
        python python-pip git wget curl base-devel nodejs npm go rust \
        nmap masscan wireshark-cli wireshark-qt tcpdump \
        hashcat john aircrack-ng hydra sqlmap nikto metasploit \
        burpsuite zaproxy gobuster ffuf wfuzz dirb exploitdb \
        binwalk foremost steghide exiftool radare2 gdb ghidra \
        snort suricata aide rkhunter clamav chkrootkit lynis fail2ban \
        ufw iptables nftables tripwire htop iotop nethogs iftop glances \
        sysstat logwatch rsyslog auditd \
    && pacman -Scc --noconfirm

RUN pip install --no-cache-dir \
    impacket crackmapexec bloodhound pwntools scapy paramiko requests beautifulsoup4 lxml \
    volatility3 yara-python sigma-cli splunk-sdk elasticsearch loguru pandas numpy

RUN useradd -m -s /bin/bash syndra
USER syndra
WORKDIR /workspace

CMD ["bash"]
