"""
Syndra security profile color themes.
Each profile has its own CSS palette applied by the CSS preprocessor in main.py.
"""

# Maps CSS variable names to hex values per profile
THEMES: dict[str, dict[str, str]] = {
    "blue-team": {
        "--foreground":      "#a8d4f5",
        "--background":      "#050b14",
        "--cursor":          "#4da6ff",
        "--primary":         "#4da6ff",
        "--on-primary":      "#050b14",
        "--secondary":       "#00ccff",
        "--on-secondary":    "#050b14",
        "--tertiary":        "#66b3ff",
        "--on-tertiary":     "#050b14",
        "--surface":         "#0a1628",
        "--surface-bright":  "#122240",
        "--surface_bright":  "#122240",
        "--error":           "#ff6b6b",
        "--error-dim":       "#cc4444",
        "--on-error":        "#050b14",
        "--error-container": "#330000",
        "--outline":         "#1a3a5c",
        "--shadow":          "#020810",
        "--red":             "#ff6b6b",  "--red-dim":     "#cc4444",
        "--green":           "#4dffaa",  "--green-dim":   "#33cc88",
        "--yellow":          "#ffcc55",  "--yellow-dim":  "#ccaa33",
        "--blue":            "#4da6ff",  "--blue-dim":    "#3385cc",
        "--magenta":         "#cc66ff",  "--magenta-dim": "#aa44cc",
        "--cyan":            "#00ccff",  "--cyan-dim":    "#00aacc",
        "--white":           "#a8d4f5",
    },
    "red-team": {
        "--foreground":      "#ffb3b3",
        "--background":      "#110000",
        "--cursor":          "#ff3333",
        "--primary":         "#ff3333",
        "--on-primary":      "#110000",
        "--secondary":       "#ff6600",
        "--on-secondary":    "#110000",
        "--tertiary":        "#ff4d00",
        "--on-tertiary":     "#110000",
        "--surface":         "#1a0505",
        "--surface-bright":  "#2d0a0a",
        "--surface_bright":  "#2d0a0a",
        "--error":           "#ff6666",
        "--error-dim":       "#cc4444",
        "--on-error":        "#110000",
        "--error-container": "#4a0000",
        "--outline":         "#4a1010",
        "--shadow":          "#0a0000",
        "--red":             "#ff3333",  "--red-dim":     "#cc2222",
        "--green":           "#44cc66",  "--green-dim":   "#338844",
        "--yellow":          "#ffaa33",  "--yellow-dim":  "#cc8822",
        "--blue":            "#3399ff",  "--blue-dim":    "#2277cc",
        "--magenta":         "#cc44ff",  "--magenta-dim": "#aa22cc",
        "--cyan":            "#33ccff",  "--cyan-dim":    "#22aacc",
        "--white":           "#ffdddd",
    },
    "purple": {
        "--foreground":      "#e0d5f0",
        "--background":      "#0d0b14",
        "--cursor":          "#b39ddb",
        "--primary":         "#b39ddb",
        "--on-primary":      "#0d0b14",
        "--secondary":       "#9c7fc0",
        "--on-secondary":    "#0d0b14",
        "--tertiary":        "#c9a8e8",
        "--on-tertiary":     "#0d0b14",
        "--surface":         "#1a1628",
        "--surface-bright":  "#252038",
        "--surface_bright":  "#252038",
        "--error":           "#f28b82",
        "--error-dim":       "#cc6b64",
        "--on-error":        "#0d0b14",
        "--error-container": "#3d1a22",
        "--outline":         "#3d3158",
        "--shadow":          "#0d0b14",
        "--red":             "#f28b82",  "--red-dim":     "#cc6b64",
        "--green":           "#81c995",  "--green-dim":   "#5fa876",
        "--yellow":          "#fdd663",  "--yellow-dim":  "#d4b24a",
        "--blue":            "#8ab4f8",  "--blue-dim":    "#6a94d8",
        "--magenta":         "#b39ddb",  "--magenta-dim": "#9c7fc0",
        "--cyan":            "#78d9ec",  "--cyan-dim":    "#58b9cc",
        "--white":           "#e0d5f0",
    },
    "green": {
        "--foreground":      "#a8ffb3",
        "--background":      "#001100",
        "--cursor":          "#00cc44",
        "--primary":         "#00cc44",
        "--on-primary":      "#001100",
        "--secondary":       "#00ff88",
        "--on-secondary":    "#001100",
        "--tertiary":        "#33cc55",
        "--on-tertiary":     "#001100",
        "--surface":         "#001a00",
        "--surface-bright":  "#002800",
        "--surface_bright":  "#002800",
        "--error":           "#ff6666",
        "--error-dim":       "#cc4444",
        "--on-error":        "#001100",
        "--error-container": "#330000",
        "--outline":         "#004400",
        "--shadow":          "#000a00",
        "--red":             "#ff6666",  "--red-dim":     "#cc4444",
        "--green":           "#00cc44",  "--green-dim":   "#009933",
        "--yellow":          "#ccff44",  "--yellow-dim":  "#aacc33",
        "--blue":            "#44aaff",  "--blue-dim":    "#3388cc",
        "--magenta":         "#cc44ff",  "--magenta-dim": "#aa22cc",
        "--cyan":            "#00ffcc",  "--cyan-dim":    "#00ccaa",
        "--white":           "#ccffdd",
    },
    "root-me": {
        "--foreground":      "#c4cfe0",
        "--background":      "#0a0d12",
        "--cursor":          "#8a9bb5",
        "--primary":         "#8a9bb5",
        "--on-primary":      "#0a0d12",
        "--secondary":       "#a0adc4",
        "--on-secondary":    "#0a0d12",
        "--tertiary":        "#6d7b94",
        "--on-tertiary":     "#0a0d12",
        "--surface":         "#141a24",
        "--surface-bright":  "#202836",
        "--surface_bright":  "#202836",
        "--error":           "#f28b82",
        "--error-dim":       "#cc6b64",
        "--on-error":        "#0a0d12",
        "--error-container": "#3d1a22",
        "--outline":         "#2a3344",
        "--shadow":          "#070a0e",
        "--red":             "#f28b82",  "--red-dim":     "#cc6b64",
        "--green":           "#88c584",  "--green-dim":   "#6ba668",
        "--yellow":          "#dbc492",  "--yellow-dim":  "#b8a378",
        "--blue":            "#8a9bb5",  "--blue-dim":    "#6d7b94",
        "--magenta":         "#b0a8c8",  "--magenta-dim": "#9089a8",
        "--cyan":            "#90b0c0",  "--cyan-dim":    "#7090a0",
        "--white":           "#e0e6f0",
    },
    "default": {
        "--foreground":      "#cdd6f4",
        "--background":      "#0a0e14",
        "--cursor":          "#cdd6f4",
        "--primary":         "#89b4fa",
        "--on-primary":      "#0a0e14",
        "--secondary":       "#89dceb",
        "--on-secondary":    "#0a0e14",
        "--tertiary":        "#cba6f7",
        "--on-tertiary":     "#0a0e14",
        "--surface":         "#131825",
        "--surface-bright":  "#1e2a3a",
        "--surface_bright":  "#1e2a3a",
        "--error":           "#f38ba8",
        "--error-dim":       "#d4708a",
        "--on-error":        "#0a0e14",
        "--error-container": "#6b1a2a",
        "--outline":         "#2a3a52",
        "--shadow":          "#0d1117",
        "--red":             "#f38ba8",  "--red-dim":     "#d4708a",
        "--green":           "#a6e3a1",  "--green-dim":   "#88c584",
        "--yellow":          "#f9e2af",  "--yellow-dim":  "#dbc492",
        "--blue":            "#89b4fa",  "--blue-dim":    "#6b96dc",
        "--magenta":         "#cba6f7",  "--magenta-dim": "#ad88d9",
        "--cyan":            "#89dceb",  "--cyan-dim":    "#6bbece",
        "--white":           "#cdd6f4",
    },
}

# Maps config profile key → theme key
PROFILE_THEMES: dict[str, str] = {
    "blue-team":  "blue-team",
    "red-team":   "red-team",
    "purple":     "purple",
    "root-me":    "root-me",
    "custom":     "green",
    "green":      "green",
    "default":    "default",
}

# Badge colors shown in the bar (bg, fg)
PROFILE_BADGES: dict[str, tuple[str, str]] = {
    "blue-team":  ("#4da6ff", "#020810"),
    "red-team":   ("#ff3333", "#0a0000"),
    "purple":     ("#a64dff", "#060010"),
    "root-me":    ("#8a9bb5", "#070a0e"),
    "custom":     ("#00cc44", "#000a00"),
    "green":      ("#00cc44", "#000a00"),
    "default":    ("#89b4fa", "#0d1117"),
}

# Display labels
PROFILE_LABELS: dict[str, str] = {
    "blue-team":  "Blue Team",
    "red-team":   "Red Team",
    "purple":     "Purple Team",
    "root-me":    "Root-Me",
    "custom":     "Personnalisé",
    "green":      "Green",
    "default":    "Default",
}


def get_theme(profile: str) -> dict[str, str]:
    """Return the color palette for a profile key."""
    theme_key = PROFILE_THEMES.get(profile, "default")
    return THEMES.get(theme_key, THEMES["default"])
